services:
  postgres:
    image: postgres:17

    container_name: slumberspot-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 88888888
      POSTGRES_DB: slumberspot_db

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: slumberspot-backend

    restart: always

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:88888888@postgres:5432/slumberspot_db
      JWT_SECRET: itsjwtsecretboi

    ports:
      - "3000:3000"

volumes:
  postgres-data:

